---
- hosts: all
  become: yes
  task:
  - name: update packages and  install apache2 in the system
    package:
        name:  httpd
        state: present

  - name: restart the apache server
    service:
        name: httpd
        state: restarted

  - name: install apache packages
    package: 
        name: "{{ item }}"
        state: present
    loop:
      -  php
      - libapache2-mod-php
      - php-mysql
  - name: restart apache again
    service:
        name: httpd
        state: restarted
  