---
- hosts: all
  become: yes
  tasks: 
  - name: install apache server
    package:
       name: apache2
       state: present
    notify:
    - restart apache2
  - name: install php packages
    package:
       name: "{{ item }}"
       state: present
    loop:
    - php
    - libapache2-mod-php
    - php-mysql
    notify:
    - restart apache2
  handlers:
  - name: restart apache2
    service:
       name: apache2
       state: restarted  