---
- hosts: all
  become: yes
  tasks:
  - name: uninstall packages
    package:
      name: "{{  item  }}"
      state: absent
    loop:
    - "{{ webserver_package }}"
    - php
    - php-mysql
  