---
- hosts: all
  become: yes
  tasks:
  - name: install apache 
    package: 
      name: "{{ service_package}}"
      state: present
    notify:
    - restart apache 
  - name: install php packages
    package:
      name: "{{  item  }}"
      state: present
    loop:
    - php
    - php-mysql
    notify:
    - restart apache
  handlers:
  - name: restart apache 
    service:
      name: "{{ service_package}}"
      state: restarted  
